language: python
python:
  - 3.4

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - export PKG_CONFIG_PATH=/home/travis/minicoda3/lib/pkgconfig:$PKG_CONFIG_PATH
  - conda update --yes conda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - sudo -E apt-get -yq update > ~/apt-get-update.log 2>&1
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install swig

# Install packages
install:
  - conda install --yes numpy scipy matplotlib lxml nose configobj
  - pip install python-igraph
  - make -C cacti-p

# Run test
script:
  - nosetests