sudo: false
addons:
  apt:
    sources:
      - igraph
    packages:
      - swig
      - libigraph
      - libigraph-dev
language: python
python:
  - 3.4

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - export PKG_CONFIG_PATH=/home/travis/miniconda3/lib/pkgconfig:$PKG_CONFIG_PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes numpy scipy matplotlib lxml nose configobj
  - pip install python-igraph
  - pip install coveralls
  - make -C cacti-p

# Run test
script:
  - nosetests --with-coverage --cover-package=lumos
after_success:
  - coveralls